In [1]:
import numpy as np
import torch
import utils
import json
import cv2
import RPN

ImportError: dlopen(/Users/ysk/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/ysk/anaconda3/lib/python3.6/site-packages/torch/lib/libTH.1.dylib
  Reason: image not found

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
RPN_ANCHOR_SCALES = (50, 100, 150, 200, 250)
RPN_ANCHOR_RATIOS = [0.5, 1, 2]
BACKBONE_SHAPES = np.array([[128,128], [64, 64], [32, 32], [16, 16], [8, 8]])
BACKBONE_STRIDES = [4, 8, 16, 32, 64]

In [4]:
anchors = utils.generate_pyramid_anchors(RPN_ANCHOR_SCALES, RPN_ANCHOR_RATIOS, BACKBONE_SHAPES, BACKBONE_STRIDES, 1)

In [5]:
boxes_list = json.load(open('image/Annotation/RGB/bbox_list.txt', 'r'))
image_path = 'D:\\PythonPro\\Mask_RCNN-ysk\\image\\RGB\\'
box_path = 'D:\\PythonPro\\Mask_RCNN-ysk\\image\\Annotation\\RGB\\'
dataset = utils.DataSet(boxes_list, image_path, box_path)

In [6]:
dataset.add_image('20171215162635848.bmp')
img = dataset.get_image(0)

In [7]:
creator = utils.AnchorCreator(anchors)

In [8]:
labels = creator.create_anchors(dataset.get_labels_and_boxes(0))

In [9]:
rpn = RPN.Faster_RCNN(1,2)

In [10]:
img = dataset.get_image(0).reshape((1, 512, 512, 3)).astype(np.float32)
img = torch.autograd.Variable(torch.from_numpy(img).permute(0, 3, 1, 2))

In [12]:
outputs = rpn(img)

In [13]:
len(outputs)

3

In [14]:
outputs[0].shape

torch.Size([1, 65472, 2])

In [15]:
anchors.shape

(65472, 4)

In [16]:
r_loss = RPN.rpn_loss()

In [17]:
r_loss(outputs[0], labels)

Variable containing:
 0.6653
[torch.FloatTensor of size 1]

In [18]:
a = np.zeros((1, 6,3,3))
cnt = 1
for i in range(3):
    for j in range(3):
        for k in range(6):
            a[0,k,i,j] = cnt
            cnt += 1
print(a)

[[[[  1.   7.  13.]
   [ 19.  25.  31.]
   [ 37.  43.  49.]]

  [[  2.   8.  14.]
   [ 20.  26.  32.]
   [ 38.  44.  50.]]

  [[  3.   9.  15.]
   [ 21.  27.  33.]
   [ 39.  45.  51.]]

  [[  4.  10.  16.]
   [ 22.  28.  34.]
   [ 40.  46.  52.]]

  [[  5.  11.  17.]
   [ 23.  29.  35.]
   [ 41.  47.  53.]]

  [[  6.  12.  18.]
   [ 24.  30.  36.]
   [ 42.  48.  54.]]]]


In [22]:
b = torch.from_numpy(a.astype(np.float32))

In [21]:
c = b.permute(0, 2,3,1).contiguous().view(0, -1, 2)

RuntimeError: invalid argument 2: size '[0 x -1 x 2]' is invalid for input with 54 elements at D:\pytorch\pytorch\torch\lib\TH\THStorage.c:37

In [23]:
c = b.permute(0, 2,3,1)
c.shape

torch.Size([1, 3, 3, 6])

In [27]:
a = np.array([1,2,3])
b = np.array([5,6])
c = np.concatenate([a, b])
c

array([1, 2, 3, 5, 6])

In [1]:
import numpy as np

In [2]:
a = np.arange(9).reshape((3,3))
a[:, 1:3] = 0
a

array([[0, 0, 0],
       [3, 0, 0],
       [6, 0, 0]])

In [ ]:
index = a[:, 0] == 1

In [48]:
a[index]

array([[1, 0],
       [1, 0]])

In [53]:
a = np.arange(9).reshape((3,3))
print(a)
print(a - np.array)

array([ 1.,  2.,  3.,  5.,  6.])

In [54]:
index = np.where(a > 100)

In [55]:
index

(array([], dtype=int64),)

In [56]:
b = a[index]

In [57]:
b.ex

array([], dtype=float64)

In [3]:
import numpy as np

In [6]:
a = np.random.randint(10, size=(3, 4))
b = np.random.randint(10, size=(3, 4))
c = np.zeros((3,4))
print(a)
print(b)

[[2 8 5 4]
 [3 2 7 9]
 [9 0 1 1]]
[[0 3 5 4]
 [5 3 4 1]
 [0 9 2 3]]


In [9]:
d = np.array([1,2,3])

In [10]:
c[:, 0] = d
c

array([[  1.,   0.,   8.,   0.],
       [  2.,   0.,  10.,   0.],
       [  3.,   0.,   4.,   0.]])